// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ConcreteContentTypes.Core.Templates.Classes
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using ConcreteContentTypes.Core.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Dave\Source\Repos\ConcreteContentTypes\ConcreteContentTypes.Core\Templates\Classes\ServiceBaseClassTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class ServiceBaseClassTemplate : ServiceBaseClassTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nusing ConcreteContentTypes.Core.Interfaces;\r\nusing System;\r\nusing Umbraco.Core;" +
                    "\r\nusing Umbraco.Core.Models;\r\nusing Umbraco.Core.Services;\r\n\r\nnamespace ");
            
            #line 15 "C:\Users\Dave\Source\Repos\ConcreteContentTypes\ConcreteContentTypes.Core\Templates\Classes\ServiceBaseClassTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_nameSpace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic abstract partial class ServiceBase<T> : IModelService<IConcreteConte" +
                    "nt> where T : IConcreteContent, new()\r\n\t{\r\n\t\tpublic abstract string ContentTypeA" +
                    "lias { get; }\r\n\r\n\t\tprotected IContentService _contentService;\r\n\r\n\t\tpublic Servic" +
                    "eBase() \r\n\t\t\t: this(ApplicationContext.Current.Services.ContentService)\r\n\t\t{\r\n\t\t" +
                    "\t\r\n\t\t}\r\n\r\n\t\tpublic ServiceBase(IContentService contentService)\r\n\t\t{\r\n\t\t\t_content" +
                    "Service = contentService;\r\n\t\t}\r\n\r\n\t\tpublic T GetById(int contentId) \r\n\t\t{\r\n\t\t\tT " +
                    "result = new T();\r\n\t\t\tresult.Init(contentId);\r\n\r\n\t\t\treturn result;\r\n\t\t}\r\n\r\n\t\tpub" +
                    "lic T Create(IConcreteContent parent, string name, int userId = 0)\r\n\t\t{\r\n\t\t\tretu" +
                    "rn Create(parent.Id, name, userId);\r\n\t\t}\r\n\r\n\t\tpublic T Create(int parentId, stri" +
                    "ng name, int userId = 0)\r\n\t\t{\r\n\t\t\tT result = new T();\r\n\r\n\t\t\tvar content = _conte" +
                    "ntService.CreateContentWithIdentity(name, parentId, result.ContentTypeAlias, use" +
                    "rId);\r\n\r\n\t\t\tresult.Name = name;\r\n\t\t\tresult.ParentId = parentId;\r\n\t\t\tresult.Id = " +
                    "content.Id;\r\n\r\n\t\t\treturn result;\r\n\t\t}\r\n\r\n\t\tpublic IContent GetIContent(T content" +
                    ")\r\n\t\t{\r\n\t\t\tvar dbContent = _contentService.GetById(content.Id);\r\n\r\n\t\t\tif (conten" +
                    "t != null)\r\n\t\t\t\treturn dbContent;\r\n\r\n\t\t\tthrow new InvalidOperationException(\"Con" +
                    "tent Id \" + content.Id + \" not found.\");\r\n\t\t}\r\n\r\n\t\tpublic void Save(T content, i" +
                    "nt userId = 0, bool raiseEvents = true)\r\n\t\t{\r\n\t\t\tIContent dbContent = GetIConten" +
                    "t(content);\r\n\r\n\t\t\tSetDbProperties(content, dbContent);\r\n\r\n\t\t\t_contentService.Sav" +
                    "e(dbContent, userId, raiseEvents);\r\n\t\t}\r\n\r\n\t\tpublic Attempt<Umbraco.Core.Publish" +
                    "ing.PublishStatus> SaveAndPublishWithStatus(T content, int userId = 0, bool rais" +
                    "eEvents = true)\r\n\t\t{\r\n\t\t\tvar dbContent = GetIContent(content);\r\n\r\n\t\t\tSetDbProper" +
                    "ties(content, dbContent);\r\n\r\n\t\t\treturn _contentService.SaveAndPublishWithStatus(" +
                    "dbContent, userId, raiseEvents);\r\n\t\t}\r\n\r\n\t\tpublic void Delete(T content, int use" +
                    "rId = 0)\r\n\t\t{\r\n\t\t\tIContent dbContent = GetIContent(content);\r\n\r\n\t\t\t_contentServi" +
                    "ce.Delete(dbContent, userId);\r\n\t\t}\r\n\r\n\t\tpublic virtual IContent SetDbProperties(" +
                    "T content, IContent dbContent)\r\n\t\t{\r\n\t\t\tdbContent.Name = content.Name;\r\n\r\n\t\t\tret" +
                    "urn dbContent;\r\n\t\t}\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class ServiceBaseClassTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
